#!/usr/bin/env python3
#
# Part of libximodem's build system.
#
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Jason Hill
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use
# this file except in compliance with the License. You may obtain a copy at
# http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law
# or agreed to in writing, software distributed under the License is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.
#
# disclosure: ai-assisted (claude-sonnet-5), manual review -- see AI_DISCLOSURE.md
"""Generate the Zimodem unity-build translation unit + a best-effort prototype
header, mimicking what the Arduino build does (concatenate all .ino, main sketch
first, and auto-declare every free function).
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
# The buildable sketch is reconstructed by scripts/patch_firmware.py from the pinned
# upstream snapshot (external/) + patches/. Run it first if it hasn't been.
FW = os.path.join(ROOT, "build", "vendor", "firmware")
FW_INC = "../../build/vendor/firmware"   # relative to src/generated/unity.cpp
OUT_DIR = os.path.join(ROOT, "src", "generated")
MAIN = "zimodem.ino"

if not os.path.isdir(FW):
    import subprocess
    subprocess.run([sys.executable, os.path.join(HERE, "patch_firmware.py")], check=True)

os.makedirs(OUT_DIR, exist_ok=True)

inos = sorted(f for f in os.listdir(FW) if f.endswith(".ino"))
inos.remove(MAIN)
order = [MAIN] + inos

# Feature-disabled in the v1 host build (see firmware/PATCHES.md). Their .ino
# bodies compile to nothing, and scanning them yields prototypes referencing
# lwip/ESP-only types, so keep them out of the prototype header.
PROTO_SKIP = {
    "proto_ping.ino", "zslipmode.ino", "zpppmode.ino",
}

# --- prototype extraction --------------------------------------------------
# A definition line looks like:   [static] <ret type ...> name(args) [{]
# We reject control keywords, labels, class/struct bodies, and macro lines.
KEYWORDS = {"if", "for", "while", "switch", "return", "else", "do", "case",
            "sizeof", "new", "delete", "throw", "catch", "template"}
DEF_RE = re.compile(
    r'^([A-Za-z_][\w\s:\*&<>,]*?[\s\*&])'   # return type (greedy-ish)
    r'([A-Za-z_]\w*)\s*'                     # function name
    r'\(([^;{}]*)\)\s*'                      # (args)
    r'(\{)?\s*$')

def extract_protos(path):
    protos = []
    lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
    depth = 0            # brace depth (skip anything nested in a class/func)
    pending = None
    for i, raw in enumerate(lines):
        line = raw.rstrip()
        stripped = line.strip()
        # track brace depth crudely (ignores strings/comments; good enough here)
        if depth > 0:
            depth += line.count("{") - line.count("}")
            if depth < 0:
                depth = 0
            continue
        if (not stripped or stripped.startswith("#") or stripped.startswith("//")
                or stripped.startswith("*") or stripped.startswith("/*")
                or ":" == stripped[-1:] or stripped.startswith("}")):
            continue
        # candidate on a single line, brace same line or next line
        cand = line
        m = DEF_RE.match(cand)
        if not m:
            # try joining with the next line if this looks like a signature head
            if ("(" in cand and ")" not in cand and not cand.endswith(";")
                    and i + 1 < len(lines)):
                cand2 = cand + " " + lines[i + 1].strip()
                m = DEF_RE.match(cand2)
        if m:
            ret, name, args, brace = m.group(1), m.group(2), m.group(3), m.group(4)
            ret_first = ret.split()[0] if ret.split() else ""
            if (name not in KEYWORDS and ret_first not in KEYWORDS
                    and "::" not in name and "=" not in args
                    and not ret.strip().startswith("return")):
                decl = f"{ret.strip()} {name}({args.strip()});"
                # collapse whitespace
                decl = re.sub(r"\s+", " ", decl)
                protos.append(decl)
            if brace == "{" or (m.re is DEF_RE and cand.endswith("{")):
                depth = 1
        elif re.match(r'^(static\s+)?(class|struct|namespace|enum)\b', stripped):
            if "{" in line and "}" not in line:
                depth = 1
    return protos

all_protos = []
seen = set()
for f in [x for x in order if x not in PROTO_SKIP]:
    for p in extract_protos(os.path.join(FW, f)):
        if p not in seen:
            seen.add(p)
            all_protos.append(p)

with open(os.path.join(OUT_DIR, "xi_prototypes.h"), "w") as fh:
    fh.write("// AUTO-GENERATED by scripts/gen_unity.py -- do not edit.\n")
    fh.write("#ifndef XI_PROTOTYPES_H\n#define XI_PROTOTYPES_H\n\n")
    for p in all_protos:
        fh.write(p + "\n")
    fh.write("\n#endif\n")

with open(os.path.join(OUT_DIR, "unity.cpp"), "w") as fh:
    fh.write("// AUTO-GENERATED by scripts/gen_unity.py -- do not edit.\n")
    fh.write('#include "../xi_prelude.h"\n\n')
    fh.write('// zimodem.ino self-includes generated/xi_prototypes.h after its headers.\n')
    fh.write('#include "%s/%s"\n' % (FW_INC, MAIN))
    for f in inos:
        fh.write('#include "%s/%s"\n' % (FW_INC, f))

print("generated %d prototypes from %d .ino files" % (len(all_protos), len(order)))
